### ISSUE TITLE
Arizona link on knit cv 

### ISSUE THREAD

**Issue by kparrish92** [jvcasill/academic_cv#7]
After knitting, the text on the pdf that says "Rutgers" takes you to the UA website.

**Comment by jvcasillas** [comment]
Found. Check line 67 of 'assets/tex/preamble.tex'

**Comment by kparrish92** [comment]
I see it!

**Comment by jvcasillas** [comment]
Keeping open so i remember to fix 😆

**Comment by jvcasillas** [comment]
finally fixed via https://github.com/jvcasillas/cv/commit/d68118ecf8f681ec9977d823e2a75ce95bb0f199

Thanks @kparrish92
